export enum TimeZone {
    AmericaAraguaina = "America/Araguaina",
    AmericaBahia = "America/Bahia",
    AmericaBelem = "America/Belem",
    AmericaBoaVista = "America/Boa_Vista",
    AmericaCampoGrande = "America/Campo_Grande",
    AmericaCuiaba = "America/Cuiaba",
    AmericaFortaleza = "America/Fortaleza",
    AmericaMaceio = "America/Maceio",
    AmericaManaus = "America/Manaus",
    AmericaPortoVelho = "America/Porto_Velho",
    AmericaRecife = "America/Recife",
    AmericaRioBranco = "America/Rio_Branco",
    AmericaSaoPaulo = "America/Sao_Paulo",
}